# get http://localhost:3000/api/revenues/Betty
# Content-Type: application/json

# {
#     "username":"Betty",
#     "amount":11000,
#     "forFix":"5f1629feeef0803f8c6c5534"
# }

# post http://localhost:3000/api/revenues
# Content-Type: application/json

# {
#     "username":"Betty3",
#     "amount":2000,
#     "referral":"Betty"
# }


put http://localhost:5000/api/sales/cancellation
Content-Type: application/json

{
    "username":"Smith",
    "order_id":1
}

# post http://localhost:5000/api/orderChats
# Content-Type: application/json

# {
#     "from":"Betty",
#     "to":"Smith",
#     "message":"Nothing to say",
#     "order_id":2
# }

